#! /bin/bash
# Copyright 2014 Peter Williams <peter@newton.cx>
# Licensed under the GNU General Public License, version 3 or higher.
#
# Drive (xe)latex sensibly

# I stash the annoying LaTeX output files in a hidden directory called
# .latexwork. However, some LaTeX distributions refuse to write to hidden
# paths by default. I figured out how to hack the configuration, but that's
# not a scalable solution. Instead I just create a temporary symlink with an
# acceptable name -- good jorb security.

workdir=.latexwork
workalias=_latexwork
engine=pdflatex
args="-interaction nonstopmode -halt-on-error -file-line-error"
dobibtex=false
dobibexport=false

while [ $# -gt 0 ] ; do
    case "$1" in
	-x) engine=xelatex ;;
	-b) dobibtex=true ;;
	-l) args="$args -papersize letter" ;;
	-e*) dobibtex=true ; dobibexport=true ; bestyle="${1#-e}" ;;
	*) break ;;
    esac
    shift
done

if [ $# -ne 2 ] ; then
    echo >&2 "usage: latexdriver [-x] [-b] [-l] [-eSTYLE] input.tex output.pdf"
    exit 1
fi

input="$1"
output="$2"

if [ ! -e "$input" ] ; then
    echo >&2 "error: input \"$input\" does not exist"
    exit 1
fi

base=$(echo "$input" |sed -e 's/\.[^.]*$//')

if [ -z "$base" ] ; then
    echo >&2 "error: failed to strip extension from input path \"$input\""
    exit 1
fi

job="$workalias/$base"
tlog="$workalias/$base.hllog" # "highlevel log"
blog="$workalias/$base.hlblg" # bibtex version thereof

mkdir -p $workdir
ln -sf $workdir $workalias || exit 1

function logrun () {
    # $1 = command
    # $2 = boring args
    # $3 = interesting final arg
    # $4 = logfile name

    if [ -z "$2" ] ; then
	echo + $1 $3
    else
	echo + $1 ... $3
    fi

    $1 $2 $3 >&$4
    if [ $? -ne 0 ] ; then
	cat $4 >&2
	rm -f $workalias
	exit 1
    fi
}

logrun $engine "$args -jobname $job" $base $tlog
if $dobibtex ; then
    if $dobibexport ; then
	echo + bib btexport $bestyle $job.aux '>'$base.bib
	bib btexport $bestyle $job.aux >$base.bib || exit 1
    fi

    logrun bibtex "" $job $blog
    grep Warning $blog >&2
    # force at least one extra run:
    logrun $engine "$args -jobname $job" $base $tlog
fi

# deluxetables seem to always tell you to rerun latex. Stripping out
# lines containing "longtable" makes us ignore them.

n=0

while grep -v longtable $tlog |grep -q Rerun ; do
    logrun $engine "$args -jobname $job" $base $tlog
    if [ $n -gt 10 ] ; then
	echo >&2 "error: too many iterations; check $tlog"
	rm -f $workalias
	exit 1
    fi
    n=$(($n + 1))
done

mv $job.pdf "$output"
exec rm -f $workalias
